title: "Pranav Unnikrishnan"
description: "Evolutionary biology • science communication • science art"
url: "https://upranav13.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: aqua

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

author:
  name: "Pranav Unnikrishnan"
  avatar: "/assets/images/avatar.jpg"
  bio: "Evolutionary Biologist | Research, Design & Illustration"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:upranav13@gmail.com"

    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0003-8532-6324"

    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=CxkQ2ysAAAAJ"

    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Pranav-Unnikrishnan-2"
